### PR TITLE
Update to work with Loboris MicroPython

### PR DESCRIPTION
**Pull request by torntrousers**
As per https://github.com/MZachmann/LightLora_MicroPython/issues/5

### CODE REVIEW

**Comment by MZachmann** [comment]
two small requests, if you would...
1) have the flag named self.isLoboris and set it after irqPin is set in __init__ . I don't know the overhead of checking for irq but no sense doing it more than once. So, as in:
		self.isLoboris = not callable(getattr(self.irqPin, "irq", None)) # Loboris build or upython?

2) in the last changed line use self.irqPin.irq(handler=None, trigger=0) which is strictly cosmetic


Thanks for helping out.

**Comment by torntrousers** [comment]
Done.

**Comment by MZachmann** [comment]
you didn't actually make change (2) above but it's not worth fussing with.

**Comment by torntrousers** [comment]
Oh. i thought it was the ```trigger=0``` missing that you meant but there's a typo of handlefn/None you meant isn't there!

**Pull request merged**
